name: Broken Bypass
description: A bypass is misbehaving or no-longer working
labels: [Broken-bypass]
body:
- type: markdown
  attributes:
    value: |
      ## Note
      Issues are not a place to go ask support questions.
      Please ask support questions on the [Discord](https://discord.gg/RSAf7b5njt).
      
      ### **Please don't submit multiple issue about the same website. [Search](https://github.com/FastForwardTeam/FastForward/labels/Broken-bypass) if the domain has been reported before filing the issue.**
      Thanks for taking the time to fill out this form!
- type: input
  id: domain
  attributes:
    label: Domain
    description: Submit one website only.
    placeholder: 'Just the name of the site. example: https://google.com'
  validations:
    required: true
- type: input
  id: site
  attributes:
    label: Link
    description: Submit the exact link you are on.
    placeholder: 'Example: https://www.google.com/webhp'
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the extension are you running? You can check the extension version by clicking on the extension name and looking at the top left corner.
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Brave
      - Microsoft Edge
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: What OS are you seeing the problem on?
    options:
      - Windows
      - Linux
      - MacOS 
- type: textarea
  attributes:
    label: Anything else?
    description: |
       Images? Videos? Anything that will give us more context about the issue you are encountering!

       Tip: You can attach images files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
