name: Bug report
title: [Bug]
description: Something is not working in the extension
labels: [Bug]
body:
- type: markdown
  attributes:
    value: |
      ## Note
      Issues are not a place to go ask support questions.
      Please ask support questions on the [Discord](https://discord.gg/RSAf7b5njt).
      
      ### **This form is not for reporting sites that are not bypassed**
      Thanks for taking the time to fill out this form!
- type: textarea
  id: body
  attributes:
    label: Body
    description: Description of the issue you are facing
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of the extension are you running?
    options:
      - Manifest-v2
      - Manifest-v3
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browser(s) are you seeing the problem on?
    multiple: true
    options:
      - Firefox browsers
      - Chrome browsers (includes brave, edge, opera, etc)
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: What platform are you seeing the problem on?
    options:
      - Computer (Windows, Linux, MacOS)
      - Phone (Android)
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
       Images? Videos? Anything that will give us more context about the issue you are encountering!

       Tip: You can attach images files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
