name: Pull_req

on: pull_request

jobs:
  Chromium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # pulls all commits (needed for commits to version)
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Make package
        run: node ./scripts/build.js chromium nover

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FastForward_chromium
          path: build/dist
          if-no-files-found: error

  Firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Make package
        run: node ./scripts/build.js firefox nover

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FastForward_firefox
          path: build/dist
          if-no-files-found: error
